from utils.classes import *

G = Graph()
G.addNeuron(Neuron(vecteur=type_1[1]))
G.plotGraph()
G.addNeuron(Neuron(vecteur=type_2[2]))
G.plotGraph()
G.addNeuron(Neuron(vecteur=type_2[3]))
G.plotGraph()
G.addNeuron(Neuron(vecteur=type_1[2]))
G.plotGraph()
G.addNeuron(Neuron(vecteur=type_1[4]))
G.plotGraph()
G.addNeuron(Neuron(vecteur=type_2[5]))
G.plotGraph()
G.addNeuron(Neuron(vecteur=type_1[3]))
G.plotGraph()
G.addNeuron(Neuron(vecteur=type_1[5]))
G.plotGraph()
G.addNeuron(Neuron(vecteur=type_2[1]))
G.plotGraph()
G.addNeuron(Neuron(vecteur=type_2[4]))
G.plotGraph()
